# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

version: "2"

services:
  edward:
    build: .
    image: edward
    container_name: ${NAME}
    volumes:
     - "~/work:/home/jovyan/work"
    ports:
      - "${PORT}:8888"
    environment:
      GRANT_SUDO: "yes"
      NB_UID: 501

volumes:
  work:
    external:
      name: ${WORK_VOLUME}
