FROM jupyter/tensorflow-notebook

MAINTAINER Idrees Khan <idreeskhan@users.noreply.github.com>

USER $NB_USER

# Install Python 3 Edward
RUN python3 -m pip install 'edward==1.1.6'

# Install Python 2 Edward
RUN pip install 'edward==1.1.6'
