FROM jupyter/tensorflow-notebook

MAINTAINER Idrees Khan <idreeskhan@users.noreply.github.com>

USER jovyan

# Install Python 3 Theano
RUN pip3 install 'theano==0.8.2'

# Install Python 3 Edward
RUN pip3 install 'edward==1.1.6'

# Install Python 2 Theano
RUN pip2 install 'theano==0.8.2'

# Install Python 2 Edward
RUN pip2 install 'edward==1.1.6'
